"""Initial migration

Revision ID: 100b49019283
Revises: 
Create Date: 2025-03-25 07:16:48.408864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '100b49019283'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'player', ['user_id'])
    op.drop_constraint(None, 'player', type_='foreignkey')
    op.create_foreign_key(None, 'player', 'user', ['user_id'], ['id'])
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_constraint(None, 'player', type_='foreignkey')
    op.create_foreign_key(None, 'player', 'user', ['id'], ['id'])
    op.drop_constraint(None, 'player', type_='unique')
    op.drop_column('player', 'user_id')
    # ### end Alembic commands ###
