"""Add index to player_id in Subject

Revision ID: 40c1ad20556a
Revises: 7be2238fb868
Create Date: 2025-03-27 02:01:40.605500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40c1ad20556a'
down_revision: Union[str, None] = '7be2238fb868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subject')
    op.drop_table('profile')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('player_id', sa.INTEGER(), nullable=False),
    sa.Column('avatar_url', sa.VARCHAR(), nullable=True),
    sa.Column('bio', sa.VARCHAR(), nullable=True),
    sa.Column('mood', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id')
    )
    op.create_table('subject',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('player_id', sa.INTEGER(), nullable=False),
    sa.Column('code_name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('difficulty', sa.INTEGER(), nullable=False),
    sa.CheckConstraint('difficulty >= 1 AND difficulty <= 5', name='difficulty_range'),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
