"""added a quest id for each study session

Revision ID: 8221dec65b2a
Revises: be86c74b06ae
Create Date: 2025-06-28 19:53:37.595286

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8221dec65b2a"
down_revision: Union[str, None] = "be86c74b06ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("studysession", sa.Column("quest_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        None, "studysession", "quest", ["quest_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "studysession", type_="foreignkey")
    op.drop_column("studysession", "quest_id")
    # ### end Alembic commands ###
