"""updated the study session table to have actual_complete_time

Revision ID: e10580bae6a2
Revises: e48fd74021be
Create Date: 2025-06-28 17:35:32.614249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e10580bae6a2'
down_revision: Union[str, None] = 'e48fd74021be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studysession', sa.Column('actual_complete_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studysession', 'actual_complete_time')
    # ### end Alembic commands ###
